#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

local_branch_name="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex='^((master|release|develop|feat|fix|chore|refactor|test)(\/#[0-9]+|\/[a-z-]+|\/#[0-9]\/[a-z-]+)?)$'



if [[ ! $local_branch_name =~ $valid_branch_regex ]]; then
    echo "There is something wrong with your branch name."
    echo "Branch names in this project must adhere to this contract: $valid_branch_regex."
    echo "Your commit will be rejected. You should rename your branch to a valid name and try again."
    exit 1
fi

exit 0