#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
if [ -t 1 ]; then
  exec < /dev/tty
fi
read -n1 -p "[1]feat [2]fix [3]docs [4]refactor [5]test [6]chore >> " category
echo ""
read -n1 -p "related to do on the to do: " toDo
toDoVar=""
if [[ "$toDo" =~ ^[0-9]+$ ]]; then
  toDoVar="_\$${toDo}"
fi
case ${category} in
  1) category="feat" ;;
  2) category="fix" ;;
  3) category="docs" ;;
  4) category="refactor" ;;
  5) category="test" ;;
  6) category="chore" ;;
esac

COMMIT_MSG_FILE=$1

branch_name=`git rev-parse --abbrev-ref HEAD`
issue_number=`echo ${branch_name} | cut -d '/' -f2`
first_line=`head -n1 ${COMMIT_MSG_FILE}`


if [ -z "$first_line" ]; then
  sed -i ".bak" "1s/^/${category}(${issue_number}${toDoVar}): /" ${COMMIT_MSG_FILE}
fi